name: DevOps (CI/CD) ☁️

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '-release-')"

    steps:
      - name: Repository checkout 🛎️
        uses: actions/checkout@v2

      - name: Deploy to Heroku 🚓
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
          HD_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
