name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and deploy "DisasterRelief" application...
    runs-on: ${{ matrix.os }}
    if: "contains(github.event.head_commit.message, '-release-')"

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Configure Google Maps
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "GOOGLE_MAPS_API_KEY"
          replace: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Deploy application to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
